export const TransportMode = {
  DRIVING: "DRIVING",
  BICYCLING: "BICYCLING",
};

export const OrderStatus = {
  NEW: "NEW",
  COOKING: "COOKING",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  PICKED_UP: "PICKED_UP",
  COMPLETED: "COMPLETED",
  ACCEPTED: "ACCEPTED",
};
